# 1. 아주 간단한 버전의 MLP

## library
최소한으로 필요한 라이브러리들 선언

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## 데이터 셋 불러오기
iris 데이터셋을 활용할 예정

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
x=iris.data
y = keras.utils.to_categorical(iris.target, 3)


## 모델 구성
간단하게 모델 구성하기

In [ ]:
model = Sequential()
model.add(Dense(4, activation='relu', input_shape=(4,)))
model.add(Dense(3, activation='softmax'))
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


사용할 fuction 들을 지정

In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])


## 모델 학습 및 테스트 결과 보기
fit을 통해 학습을 하고 score 확인

In [ ]:
model.fit(x, y,
          batch_size=10,
          epochs=100,
          verbose=0
)

score = model.evaluate(x, y, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


Test loss: 0.6575832962989807
Test accuracy: 0.6933333277702332


## 적용 예
실제로 다른 꽃을 측정하여 모델에 집어 넣어 이 꽃이 어떤 것인지 알고자 할 경우

In [ ]:
x[:1,:],y[:1,:],x[60:61,:],y[60:61,:]

(array([[5.1, 3.5, 1.4, 0.2]]),
 array([[1., 0., 0.]], dtype=float32),
 array([[5. , 2. , 3.5, 1. ]]),
 array([[0., 1., 0.]], dtype=float32))

In [ ]:
x_test=np.array( [ [5.1, 3.5, 1.4, 0.2],[5. , 2. , 3.5, 1. ]])
r=model.predict(x_test)
np.argmax(r, axis=-1)

array([0, 2])